### ISSUE TITLE
command

### ISSUE THREAD

**Issue by jaan143** [Faizanf33/Video-to-audio#1]
please help me to correct my comand
i want to convert multiple files at once
python P:\Downloads\Video-to-audio-master\vi2au.py -d '/contents/New folder/LeanAnalytics' -o '/contents/New folder/music'

**Comment by Faizanf33** [comment]
Use '\\' instead of '/'

**Comment by Faizanf33** [comment]
Cannot be used on windows platform, sorry. use ubuntu server or bash script to run this file.
